import Constants from "expo-constants";

export const {
    EXPO_APP_IDENTIFIER,
    EXPO_APPWRITE_PROJECT_ID,
    EXPO_APPWRITE_DATABASE_ID,
    EXPO_APPWRITE_POSTS_COLLECTION_ID,
    EXPO_APPWRITE_STORAGE_ID,
    EXPO_APPWRITE_USERS_COLLECTION_ID,
    EXPO_APPWRITE_MESSAGES_COLLECTION_ID,
    EXPO_APPWRITE_COMMENTS_COLLECTION_ID
} = process.env;

